ci:
  autofix_prs: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']

  # Prettier for formatting TypeScript, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        entry: prettier --no-error-on-unmatched-pattern --write --ignore-unknown

  # ESLint for .ts/.tsx files
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.30.1
    hooks:
      - id: eslint
        files: \.tsx?$
        types: [file]
        additional_dependencies:
          - 'eslint@8.36.0'
          - '@typescript-eslint/eslint-plugin@5.55.0'
          - '@typescript-eslint/parser@5.55.0'
          - 'eslint-plugin-react-hooks@4.6.2'

